import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useForm } from 'react-hook-form';
import Tesseract from 'tesseract.js';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

interface PictureData {
  picture: FileList;
}

export default function Home() {
  const { register: registerPic, handleSubmit: handlePicSubmit } =
    useForm<PictureData>();

  const onSubmit = async (data: PictureData) => {
    const schedule = data.picture.item(0);
    if (schedule) {
      const imageUrl = URL.createObjectURL(schedule);
      await Tesseract.recognize(imageUrl, 'eng', {
        logger: (m) => {
          console.log(m);
          if (m.status !== 'recognizing text') return;
        },
      })
        .catch((err) => {
          console.error(err);
        })
        .then((result) => {
          if (result) {
            console.log(result.data);
          }
        });
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form onSubmit={handlePicSubmit(onSubmit)}>
          <input
            {...registerPic('picture')}
            type="file"
          />
          <button
            type="submit"
          >Upload</button>
        </form>
      </main>
    </>
  )
}
